---
- hosts: prod-centos
  remote_user: xxxxxxxxxxxxx
  become: yes
  tasks:
  - name: Install Nagios agent NRPE to all servers
    yum:
      name: nrpe
      state: latest
  - name: install nagios plugins
    yum:
      name: nagios-plugins-all
      state: latest
  - name: Start and enable NRPE
    service:
      name: nrpe
      state: started
      enabled: yes
